 import ThemeProvider from '@/provider/ThemeProvider'
import './globals.css'
import { Tajwal, Cairo } from '@/lib/fonts'
import { Toaster } from '@/components/ui/sonner'
import   NavBar  from '@/components/menu/NavBar'
import { SideBar } from '@/components/menu/SideBar'
import Footer from '@/components/menu/Footer'
import UrlProvider from '@/context/serviceProvider'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' dir='rtl' suppressHydrationWarning>
    {/* <html lang='en' dir='rtl' suppressHydrationWarning> */}
      <body
        className={`${Tajwal.variable} ${Cairo.variable} flex items-center justify-center bg-background flex-col`}
      >
         <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          // disableTransitionOnChange
        > 
          <NavBar />
          {/* <SideBar /> */}
          <UrlProvider>
          <div className='mt-[60px] flex w-full flex-col items-center justify-center px-4'>
            {children}
          </div>
          {/* <Footer/> */}
          </UrlProvider>
          <Toaster richColors position='bottom-right' closeButton />
        </ThemeProvider>
      </body>
    </html>
  )
}
